name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

    build:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
